Feature/hw 2.2/implementation
Marymezh/Navigation_New pull request #4
Opened 2021-05-23 02:30 UTC by Marymezh

2021-05-27 20:24 UTC, pankova requested changes

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
>          super.viewWillLayoutSubviews()
Если здесь не происходит дополнительной логики, в переопределении метода нет необходимости)

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +        self.view.addSubview(newButton)
Опциональное улучшение: можно настройку кнопки (добавление сабвью и задание внешнего вида) вынести в приватный метод configureButton. Если вся верстка будет в коде, а так бывает в большинстве случаев на работе, viewDidLoad будет содержать много логики, и разнесение ее по небольшим методам ускорит вникание в смысл кода :)

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +            newButton.setTitle("NEW BUTTON", for: .normal)
Необязательно делать отступ в таб, если хочется визуально разделить массивный код, можно отступать пустую строку) В целом проверять - нативно ли для среды разработки вы форматируете текст можно выделив его и нажав `Ctrl+I`

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +        NSLayoutConstraint.activate([newButton.heightAnchor.constraint(equalToConstant: 50),
Если сделать перенос после квадратной скобки, можно получить чуть аккуратней запись:
```
NSLayoutConstraint.activate([
    newButton.heightAnchor.constraint(equalToConstant: 50),
    newButton.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
    newButton.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor, constant: 0),
    newButton.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor, constant: 0)
])
```

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +                                 newButton.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
Значение constant по дефолту 0, можно сократить код и не писать этот аргумент при вызове метода, получится чуть кратче :)
`newButton.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor)`

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileHeaderVIew.swift
> +            avatarImageView.layer.cornerRadius = avatarImageView.frame.size.width/2
Здорово, что настраиваете радиус в зависимости от фрейма - при изменении длины стороны такой код не сломается 👍

2021-05-27 20:24 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +                                 newButton.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor, constant: 0),
Нижний констрейнт привязан верно, левый и правый привязаны к safeArea. Как правило leading и trailing совпадают у safeArea и вьюконтроллера, но могут и нет, например при повороте экрана, если приложение поддерживает горизонтальную ориентацию. Такие моменты можно уточнять в плане требований, чтобы продуктовые ожидания скорее совпадали с результатом :)

2021-05-31 05:36 UTC, Marymezh commented on Navigation/Profile/ProfileViewController.swift
>          super.viewWillLayoutSubviews()
то есть этот метод можно просто удалить? На лекциях просто иногда удаляют то, что не нужно, иногда оставляют. Как поступать по уму? :)

2021-05-31 05:37 UTC, Marymezh commented on Navigation/Profile/ProfileViewController.swift
> +        self.view.addSubview(newButton)
сделала отдельный метод для настройки кнопки :)

2021-05-31 05:38 UTC, Marymezh commented on Navigation/Profile/ProfileViewController.swift
> +            newButton.setTitle("NEW BUTTON", for: .normal)
про отступ в таб не очень поняла :) хочу, чтобы отступами также код был как бы разделен логически. Как сделать правильно?

2021-05-31 05:39 UTC, Marymezh commented on Navigation/Profile/ProfileViewController.swift
> +        NSLayoutConstraint.activate([newButton.heightAnchor.constraint(equalToConstant: 50),
сделала вообще по другому: вынесла все констрейнты в константу и потом просто ее активировала

2021-05-31 05:39 UTC, Marymezh commented on Navigation/Profile/ProfileViewController.swift
> +                                 newButton.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor, constant: 0),
сократила, удалила :)

2021-05-31 05:40 UTC, Marymezh commented on Navigation/Profile/ProfileHeaderVIew.swift
> +            avatarImageView.layer.cornerRadius = avatarImageView.frame.size.width/2
честно признаться, я другого способа и не знаю, как сделать кружок :)

2021-05-31 05:43 UTC, Marymezh commented on Navigation/Profile/ProfileViewController.swift
> +                                 newButton.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor, constant: 0),
убрала привязку leading и trailing constraints к SafeArea - поняла в чем разница при повороте экрана. Я так поняла, что здесь нет однозначного ответа, как сделать правильно - мне честно и так и так не очень нравится: если привязать к Safe Area, то в горизонтальном положении получаются отступы, кнопка какая-то куцая становится, а если привязать к самой Super View, то кнопка "убегает" под "ушко", тоже выглядит сомнительно...

2021-05-31 12:16 UTC, pankova commented on Navigation/Profile/ProfileHeaderVIew.swift
> +            avatarImageView.layer.cornerRadius = avatarImageView.frame.size.width/2
Всегда есть вариант присвоить константу, вроде такого: `avatarImageView.layer.cornerRadius = 6`)

2021-05-31 12:16 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +        self.view.addSubview(newButton)
Супер!

2021-05-31 12:16 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +            newButton.setTitle("NEW BUTTON", for: .normal)
Относительно строчки `self.view.addSubview(newButton)` следующая `newButton.setTitle("NEW BUTTON", for: .normal)` и дальнейшие сдвинуты вправо. Это весьма неклассический способ форматирования кода, непривычный многим разработчикам. Плюс он непривычен xcode (если выделить весь текст и нажать Ctrl+I - строчки выровняются обратно), а значит для его поддержки нужны дополнительные усилия, что не есть гуд). 

Желание разделить большой метод - отличное, и обычно решается разбиением на методы поменьше или отступами одной пустой строкой)

2021-05-31 12:16 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
>          super.viewWillLayoutSubviews()
На лекциях скорей всего оставляют из экономии времени, а в целом если нет дополнительной логики - нет смысла и в методе) Если посмотреть все методы [вьюконтроллера](https://developer.apple.com/documentation/uikit/uiviewcontroller) - их множество. Теоретически можно каждый переопределить, вызвать внутри метод у super и больше ничего не делать, но зачем :)

2021-05-31 12:16 UTC, pankova commented on Navigation/Profile/ProfileViewController.swift
> +                                 newButton.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor, constant: 0),
Здорово, что проверили! В итоге можете сделать на свое усмотрение) В рабочих проектах такие моменты обсуждаются с дизайнерами) Смысл комментария был как раз в том, чтобы вы понимали разницу :)

2021-08-19 02:30 UTC, closed without merging